### PR TITLE
Made the tests functional

### PR DESCRIPTION
**Pull request by mcustiel**

### CODE REVIEW

**Comment by mcustiel** [comment]
```
→ php-tool-run codecept run  --coverage --coverage-xml --coverage-html 
RUNNING: ' codecept run --coverage --coverage-xml --coverage-html' in directory '/home/mcustiel/Development/workspaces/php/Yii2-Curl'
Codeception PHP Testing Framework v2.2.9
Powered by PHPUnit 5.7.19 by Sebastian Bergmann and contributors.

Acceptance Tests (0) --------------------------------------------------------------------------------------------------------------------------------------------------------
Running exec /app/vendor/bin/phiremock -i 127.0.0.1 -p 18080 -d
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Functional Tests (9) --------------------------------------------------------------------------------------------------------------------------------------------------------
Running exec /app/vendor/bin/phiremock -i 127.0.0.1 -p 18080 -d
✔ httpMockCest: Simple http ok test (0.05s)
✔ httpMockCest: Set get params test (0.03s)
✔ httpMockCest: Set post params test (0.02s)
✔ httpMockCest: Set post params option test (0.03s)
✔ httpMockCest: Set post params with header test (0.02s)
✔ httpMockCest: Post json test (0.03s)
✔ httpMockCest: Get with decoded json response test (0.03s)
✔ httpMockCest: Get with raw json response test (0.03s)
✔ httpMockCest: Get header param with special header separator in value (0.03s)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Unit Tests (1) --------------------------------------------------------------------------------------------------------------------------------------------------------------
Running exec /app/vendor/bin/phiremock -i 127.0.0.1 -p 18080 -d
✔ CurlTest: Init (0.01s)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 3.73 seconds, Memory: 14.00MB

OK (10 tests, 18 assertions)


Code Coverage Report:     
  2017-04-04 09:34:55     
                          
 Summary:                 
  Classes:  0.00% (0/1)   
  Methods: 47.83% (11/23) 
  Lines:   70.59% (84/119)

\linslin\yii2\curl::Curl
  Methods:  47.83% (11/23)   Lines:  70.59% ( 84/119)
Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml
****
```

**Comment by linslin** [comment]
@mcustiel many thanks for this. Could you create a pull request into develop branch?

**Comment by mcustiel** [comment]
I edited this one.

**Comment by linslin** [comment]
@mcustiel thanks. I gonne check this in the next hours. Currently stucking in some other project!

**Pull request merged**
