### PR TITLE
Added a property to store the headers

### PR DESCRIPTION
**Pull request by hugohiram**
Added a property to store the headers
Added a method to add a new header to the list
Added a method to retrieve the list of headers

### CODE REVIEW

**Comment by linslin** [comment]
Many thanks for your efforts. I see your point but I implemented this functionality in an other way. Please see https://github.com/linslin/Yii2-Curl/commit/0e2051ff67fdddd7aef50469057038eacbeff1f7 which will be released in the next `Version 1.1.4` in the next 7 days. 

Those request headers are stored as `cURL option` right now which can be used to get headers. I also added some tests to ensure stability. Don't hesitate to push more features!

In version 1.1.4 you will be able to use it like:

- `$requestHeaders = $curl->getRequestHeaders();` 
- `$aRequestHeader = $curl->getRequestHeader("string-key-of-header");`

Please note that only `private` or `protected` class vars does start with an underscore -> `public $_headers;`. Its some kind of "standard" codestyle.

**Comment by hugohiram** [comment]
Hi linslin,

Yes, my mistake, in fact that property should be protected, that is why there is a 'getHeaders' method.

Regards.

**Comment by hugohiram** [comment]
Hi linslin,

I am checking your commit and I have two comments.

The first on the 'getRequestHeader', I believe that you can call the 'getRequestHeaders' inside so you avoid duplicating the same code on both methods:

```
public function getRequestHeader($headerKey)
{
    $parsedRequestHeaders = $this->getRequestHeaders();

    return isset($parsedRequestHeaders[$headerKey]) ? $parsedRequestHeaders[$headerKey] : null;
}
```

Another is that with the current implementation, the only way to add a new header is to call the setHeaders() method and pass the full array of headers as a parameter. The main point of my proposal was to include a new method so you can add a new header at any moment. I have created the following method that uses your current implementation methods and doesn't have any impact on the class.
```
public function setHeader($key, $value)
{
    //Init
    $requestHeaders = $this->getRequestHeaders();

    $requestHeaders[$key] = $value;

    $this->setHeaders($requestHeaders);
}
```

Hope it helps.

Regards,
Hugo.

**Comment by linslin** [comment]
Thanks for your feedback. Yea, you are right. `getRequestHeaders` could be simplified. I will do this! I will also create a method to add header "step by step" while using `yii2-curl".

Many thanks for your suggestions!

**Comment by linslin** [comment]
@hugohiram yii2-curl v1.2.0 was released:

- Added `unsetHeader([string header]) [this]` helper which allows you to unset one specific header.
- Added `setHeader([string header, string value]) [this]` helper which allows you to set one specific header.
- Added `getRequestHeaders() [array]` helper which returns all request headers as an array.
- Added `getRequestHeader([string headerKey]) [string|null]`  helper which returns a specific request header as an string.

**Pull request closed without merging**
