### PR TITLE
Profiling in DEBUG mode only

### PR DESCRIPTION
**Pull request by vitalyzhakov**
Collect information about time may take resources significantly.
Developers see information in debug mode.

### CODE REVIEW

**Comment by linslin** [comment]
Hi @vitalyzhakov,

thanks for you enhancement. Could you create a pull request into dev branch? I'll release this feature in the next version.

Cheers
Lin

**Comment by vitalyzhakov** [comment]
What purpose for recreate pull in `develop` branch?

**Comment by linslin** [comment]
Gitflow Workflow - https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Comment by vitalyzhakov** [comment]
closed by #43

**Pull request closed without merging**
