### PR TITLE
(Get Request) Fix issue with _httpRequest parameters

### PR DESCRIPTION
**Pull request by yemexx1**
Remove `url` parameter used in _httpRequest call and update tests.
Update codeception bin path and remove logs_path so default is used

### CODE REVIEW

**Comment by linslin** [comment]
Thx m8

**Comment by linslin** [comment]
Well, this issue is not fully fixed right now. The testins still breaking on windows now because of: https://github.com/linslin/Yii2-Curl/issues I'll going to fix that in yii2-curl 1.1.2

**Comment by linslin** [comment]
v1.1.1 is released now: https://github.com/linslin/Yii2-Curl/releases/tag/1.1.1

**Comment by yemexx1** [comment]
Thanks @linslin. About the windows issue, I see it's because of the bin path. Had to modify it to run the tests on my Mac. Might need to make a PR to phiremock to fix it.

**Pull request merged**
